/*
 Lock 상태를 계층으로 보여준다.
 10g 이상 사용
*/
SET LINES 250
COL OWNER FOR A15
COL USERNAME FOR A15
COL SESS_INFO FOR A35
COL EVENT FOR A40
COL OBJECT_NAME FOR A35
COL OBJECT_TYPE FOR A15
COL TX_STATUS FOR A10
SELECT LPAD(' ',2*(LEVEL-1),'-')||
       S.USERNAME||'('||
       S.SID||','||
       S.SERIAL#||') Instance - '||S.INST_ID SESS_INFO,
       EVENT,
       O.OWNER||'.'||
       O.OBJECT_NAME||'('||
       O.OBJECT_TYPE||')' as OBJECT_NAME,
       T.USED_UBLK,
       T.STATUS TX_STATUS,
       S.STATUS SESS_STATUS,
       NVL(S.SQL_ID,(SELECT PREV_SQL_ID FROM GV$SESSION Z WHERE Z.INST_ID = S.INST_ID AND Z.SID = S.SID AND Z.SERIAL# = S.SERIAL#)) AS SQL_ID
       T.LOG_IO,
       T.PHY_IO
  FROM GV$SESSION S, GV$LOCKED_OBJECT LO, DBA_OBJECTS O, GV$TRANSACTION T
 WHERE S.SID = LO.SESSION_ID
   AND S.INST_ID = LO.INST_ID
   AND S.TADDR = T.ADDR(+)
   AND S.INST_ID = T.INST_ID(+)
   AND LO.OBJECT_ID = O.OBJECT_ID
/*
   AND S.USERNAME IN (SELECT USERNAME
                        FROM DBA_USERS
                       WHERE ORACLE_MAINTAINED = 'N')
*/
CONNECT BY PRIOR S.SID = S.BLOCKING_SESSION       AND
           PRIOR S.INST_ID = S.BLOCKING_INSTANCE
START WITH BLOCKING_SESSION IS NULL
;
