SET LINES 250
COL OWNER FOR A15
COL USERNAME FOR A15
COL SESS_INFO FOR A35
COL EVENT FOR A40
COL OBJECT_NAME FOR A35
COL OBJECT_TYPE FOR A15
COL TX_STATUS FOR A10
SELECT S.INST_ID,
       S.SID,
       S.SERIAL#,
       S.USERNAME,
       S.EVENT,
       S.STATUS SESS_STATUS,
       S.SQL_ID,
       S.BLOCKING_INSTANCE,
       S.BLOCKING_SESSION,
       S.BLOCKING_SESSION_STATUS
  FROM GV$SESSION S
 WHERE S.STATUS='ACTIVE'
;
