select A.COLUMN_ID,
       A.COLUMN_NAME,
       B.COMMENTS,
       A.DATA_TYPE,
       CASE WHEN A.DATA_TYPE IN ('VARCHAR2','CHAR')
                 THEN TO_CHAR(A.DATA_LENGTH)
            WHEN A.DATA_TYPE = 'NUMBER'
                 THEN CASE WHEN A.DATA_PRECISION IS NOT NULL AND A.DATA_SCALE IS NOT NULL
                                THEN DATA_PRECISION||','||DATA_SCALE
                           WHEN A.DATA_PRECISION IS NOT NULL AND A.DATA_SCALE IS NULL
                                THEN TO_CHAR(DATA_PRECISION)
                           WHEN A.DATA_PRECISION IS NULL AND A.DATA_SCALE IS NULL
                                THEN NULL
                      END
           WHEN A.DATA_TYPE = 'DATE'
                THEN NULL END AS DT_LENGTH,
       CASE A.NULLABLE WHEN 'N'
                            THEN 'NOT NULL'
                       ELSE 'NULL' END AS ISNULL,
       CASE WHEN C.COLUMN_NAME IS NOT NULL THEN 'PK' ELSE NULL END AS IS_KEY,
       A.DATA_DEFAULT
  FROM DBA_TAB_COLUMNS A, DBA_COL_COMMENTS B, DBA_CONS_COLUMNS C
WHERE A.OWNER = B.OWNER
   AND A.OWNER = C.OWNER(+)
   AND A.TABLE_NAME = C.TABLE_NAME(+)
   AND A.COLUMN_ID = C.POSITION(+)
   AND A.TABLE_NAME = B.TABLE_NAME
   AND A.COLUMN_NAME = B.COLUMN_NAME
   AND A.OWNER = :b2
   AND A.TABLE_NAME = :b1
   AND C.CONSTRAINT_NAME(+) LIKE 'PK%'
   ORDER BY A.COLUMN_ID;
   ;


SELECT INDEX_NAME,LISTAGG(COLUMN_NAME,'+') WITHIN GROUP (ORDER BY COLUMN_POSITION)
  FROM DBA_IND_COLUMNS
WHERE TABLE_OWNER = :b2
   AND TABLE_NAME =:b1
GROUP BY INDEX_NAME;


select table_name, comments from dba_tab_comments where table_name = :b1;
